### PR TITLE
update-date

### PR DESCRIPTION
**Pull request by lbraglia**
A proposed target (name can be changed) for those that always forget to update package release date (yours truly in first line)

### CODE REVIEW

**Comment by sgibb** [comment]
Nice idea but do you think this is really necessary? The `increment-version-*` targets do this automatically. But maybe we should update the date in the `release` target as well ... What do you think?

**Comment by lbraglia** [comment]
oops... didn't saw it was already implemented in `increment-version-*` :) ...

Adding `"...and update DESCRIPTION Date field"` to `increment-version-* ` documentation lines would be enough IMHO, eg. no need to change `release`.

Another point could be whether to add or not `Date:` in DESCRIPTION, if absent. 
I see no cons of adding by default, but may be wrong/"paternalistic"... In the case, docs for `increment-version-* ` could be `"...and set DESCRIPTION Date field"`

Let me know, Luca

**Comment by sgibb** [comment]
The `Date` field will added if missing. I also updated the docs.

**Comment by lbraglia** [comment]
ok, thanks!

**Pull request closed without merging**
