### PR TITLE
Lintr recipe

### PR DESCRIPTION
**Pull request by lbraglia**
A recipe for the brand new lintr

https://github.com/jimhester/lintr

### CODE REVIEW

**Comment by lgatto** [comment]
Thanks. I have not used `lintr` yet. What are its benefits compared to checking a package and sourcing/running a function other than a direct static code analysis; does it uncover other bugs?

**Comment by lbraglia** [comment]
I've started using it yesterday... currently it seems mainly a style-checking (hadley's style by default, but can be configured) package with some bits of good practices enforcing. 
It uses codetools (checkUsage) for other analysis (it's not in the default linters).  It's easy to add new linters (or to remove unused from the default ones)

Below from the devel README.md, about available linter up to now:

* `Syntax errors`: reported by [parse](http://www.inside-r.org/r-doc/base/parse).
* `object_usage_linter`: checks that closures have the proper usage using
  [codetools::checkUsage()](http://www.inside-r.org/r-doc/codetools/checkUsage).  Note this runs
  [base::eval()](http://www.inside-r.org/r-doc/base/eval) on the code, so do not use with untrusted code.
* `absolute_paths_linter`: checks that no absolute paths are used.
* `assignment_linter`: checks that `<-` is always used for assignment
* `closed_curly_linter`: check that closed curly braces should always be on their
  own line unless they follow an else.
* `commas_linter`: check that all commas are followed by spaces, but do not
  have spaces before them.
* `infix_spaces_linter`: check that all infix operators have spaces around them.
* `line_length_linter`: check the line length of both comments and code is less than
  length.
* `no_tab_linter`: check that only spaces are used, never tabs.
* `object_camel_case_linter`: check that function and variable names are not camelCase.
* `object_snake_case_linter`: check that function and variable names are not snake_case.
* `object_multiple_dots_linter`: check that function and variable names are separated by `_` rather than `.`.
* `object_length_linter`: check that function and variable names are not more than `length` characters.
* `open_curly_linter`: check that opening curly braces are never on their own
  line and are always followed by a newline.
* `single_quotes_linter`: checks that only single quotes are used to delimit
  string contestants.
* `spaces_inside_linter`: check that parentheses and square brackets do not have
  spaces directly inside them.
* `spaces_left_parentheses_linter`: check that all left parentheses have a space before them
  unless they are in a function call.
* `trailing_blank_lines_linter`: check there are no trailing blank lines.
* `trailing_whitespace_linter`: check there are no trailing whitespace characters.

**Comment by lgatto** [comment]
Thanks. I will definitely give it a go.

**Comment by sgibb** [comment]
Thanks to @lbraglia I found jimhester's [covr](https://github.com/jimhester/covr) package. IMHO that is really interesting and useful!

**Comment by lbraglia** [comment]
definitely. Now i'm using

```Makefile
covr:
        ${R} -e "library(covr); package_coverage('"$(PKGDIR)"')"
```

it's fine but would be nice to have a way to display only tests below a given percent treshold (didn't digged too much at the moment)

**Comment by lgatto** [comment]
That's looks fantastic. Will try it, thanks!

**Pull request merged**
